#!/bin/bash


USERNAME="Cat"
useradd -mG users,wheel -s /bin/bash ${USERNAME}

Info_Print "PLEASE ENTER PASSWORD :  "
read NEW_PASSWORD

# cat > PassWord.Conf <<HOSTS
# $NEW_PASSWORD
# $NEW_PASSWORD
# HOSTS

# FILE="PassWord.Conf"
# cat $FILE | passwd $USERNAME 




# SET PLYMOUTH BOOT SPLASH :
# ~~~~~~~~~~~~~~~~~~~~~~~~~~
Info_Print "SETTING PLYMOUTH BOOT SPLASH."
pacman -S --noconfirm plymouth
git clone
Done_Print "SETTING PLYMOUTH BOOT SPLASH."
echo

# systemctl enable paccache.timer &>> $LOGFILE


# Configuring /etc/mkinitcpio.conf.
info_print "Configuring /etc/mkinitcpio.conf."
cat > /mnt/etc/mkinitcpio.conf <<EOF
HOOKS=(systemd autodetect keyboard sd-vconsole modconf block sd-encrypt filesystems)
EOF

# ZRAM configuration.
info_print "Configuring ZRAM."
cat > /mnt/etc/systemd/zram-generator.conf <<EOF
[zram0]
zram-size = min(ram, 8192)
EOF


# Boot backup hook.
info_print "Configuring /boot backup when pacman transactions are made."
mkdir /mnt/etc/pacman.d/hooks
cat > /mnt/etc/pacman.d/hooks/50-bootbackup.hook <<EOF
[Trigger]
Operation = Upgrade
Operation = Install
Operation = Remove
Type = Path
Target = usr/lib/modules/*/vmlinuz

[Action]
Depends = rsync
Description = Backing up /boot...
When = PostTransaction
Exec = /usr/bin/rsync -a --delete /boot /.bootbackup
EOF