#!/bin/bash

username="Sunny"
fullname="Sunny Kumar"
userpass="\\"
shell="zsh"

arch-chroot /mnt useradd -m -G wheel -s /bin/${shell} -c ${fullname} $username
sed -i 's^# %wheel ALL=(ALL:ALL) ALL^%wheel ALL=(ALL:ALL) ALL^g' /mnt/etc/sudoers
sed -i 's^# %wheel ALL=(ALL:ALL) ALL^%wheel ALL=(ALL:ALL) ALL^g' /mnt/etc/sudoers
printf "%s\n%s" "${userpass}" "${userpass}" | arch-chroot /mnt passwd "$username"

username2="Subbu"
fullname2="Subbu Kumar"
userpass2="aa"
shell2="fish"

arch-chroot /mnt useradd -m -G wheel -s /bin/${shell2} -c ${fullname2} $username2

printf "%s\n%s" "${userpass2}" "${userpass2}" | arch-chroot /mnt passwd "$username2"



