#!/bin/bash

# -------------------------------------------------------- #
# Author : Bibhuti Bhushan                                 #
# Github : https://github.com/Bibhuti1221Bhushan/Installer #
# -------------------------------------------------------- #

# SET DISK VARIABLES :
# ~~~~~~~~~~~~~~~~~~~~
DISK=/dev/sda                            # SET DISK FOR INSTALLATION

# SET SIZE OF DRIVE :
# ~~~~~~~~~~~~~~~~~~~
BOOT_SIZE=550MiB                         # SET BOOT PARTITION SIZE
SWAP_SIZE=8GiB                           # SET SWAP PARTITION SIZE
ROOT_SIZE=35GiB                          # SET ROOT PARTITION SIZE
HOME_SIZE=                               # REMAINING SPACE FOR HOME PARTITION

# SET PACKAGES :
# ~~~~~~~~~~~~~~
KERNEL="linux-lts"                       # SET KERNEL

# SET LOG FILE :
# ~~~~~~~~~~~~~~
LOGFILE="Installer.log"

# ---------------------------------------------------------- #
# -------------------- COSMETICS THINGS -------------------- #
# ---------------------------------------------------------- #

# COLOR VARIABLES :
# ~~~~~~~~~~~~~~~~~ 
YELLOW='\e[93m'                          # YELLOW
GREEN='\e[92m'                           # GREEN
BLUE='\e[34m'                            # BLUE
RED='\e[91m'                             # RED
RESET='\e[0m'                            # RESET
BOLD='\e[1m'                             # BOLD

# PRETTY PRINT FUNCTIONS :
# ~~~~~~~~~~~~~~~~~~~~~~~~
Info_Print () {
    echo -e "${BOLD}${YELLOW}! ${GREEN}NOTE${YELLOW} ! - $1${RESET}"
}

Done_Print () {
    echo -e "${BOLD}${GREEN}! ${YELLOW}DONE${GREEN} ! - $1${RESET}"
}

Warn_Print () {
    echo -e "${BOLD}${RED}! ${BLUE}WARN${RED} ! - $1${RESET}"
}

# SHOW PROGRESS FUNCTION :
# ~~~~~~~~~~~~~~~~~~~~~~~~
Show_Progress() {
    while ps | grep $1 &> /dev/null;
    do
        echo -en "${BOLD}${GREEN} . ${RESET}"
        sleep 1
    done
}

# arch-chroot /mnt useradd -m -G wheel -s /bin/${shell2} -c ${fullname2} $username2




# useradd -G users,wheel -s /bin/bash ${username}
# chpasswd ${username} <<-EOF
# ${userpass}
# ${userpass}
# EOF

# passwd -i "Enter your new password:\nConfirm your new password:"


# passwd ${username} | cat <<EOF
# ${userpass}
# ${userpass}
# EOF




INSTLOG="Install.log"

USERNAME="Cat"

echo -en "${BOLD}${YELLOW}! ${GREEN}NOTE${YELLOW} ! - ENTER ROOT PASSWORD :  ${RESET}"
read ROOT_PASSWORD
Info_Print "SETTING ROOT PASSWORD."

# Info_Print "PLEASE ENTER PASSWORD :  "
# read NEW_PASSWORD
# useradd -mG users,wheel -s /bin/bash ${USERNAME}

# printf "%s\n%s" "${NEW_PASSWORD}" "${NEW_PASSWORD}" | passwd "$USERNAME"

# cat > PassWord.Conf <<HOSTS
# $NEW_PASSWORD
# $NEW_PASSWORD
# HOSTS


# FILE="PassWord.Conf"
# cat $FILE | passwd $USERNAME &>> $INSTLOG & Show_Progress $!

# Info_Print "INSTALLING CHROMIUM . "
# sleep 10 &>> $INSTLOG & Show_Progress $!
        
# SYNC TIME AND DATE :
# ~~~~~~~~~~~~~~~~~~~~
# echo -e "${BOLD}${YELLOW}! ${GREEN}NOTE${YELLOW} ! - SYNCING TIME AND DATE. ${RESET}"
# sudo pacman -Sy --noconfirm &>> $INSTLOG 
# Done_Print "SYNCING TIME AND DATE."
# echo


echo $NEW_PASSWORD






# SET PLYMOUTH BOOT SPLASH :
# ~~~~~~~~~~~~~~~~~~~~~~~~~~
Info_Print "SETTING PLYMOUTH BOOT SPLASH."
pacman -S --noconfirm plymouth
git clone
Done_Print "SETTING PLYMOUTH BOOT SPLASH."
echo