#!/bin/bash

username="Rishab"
fullname="Sunny Kumar"
userpass=\\
shell="zsh"

# arch-chroot /mnt useradd -m -G wheel -s /bin/${shell} -c ${fullname} $username
# sed -i 's^# %wheel ALL=(ALL:ALL) ALL^%wheel ALL=(ALL:ALL) ALL^g' /mnt/etc/sudoers
# sed -i 's^# %wheel ALL=(ALL:ALL) ALL^%wheel ALL=(ALL:ALL) ALL^g' /mnt/etc/sudoers
# printf "%s\n%s" "${userpass}" "${userpass}" | arch-chroot /mnt passwd "$username"

username2="Subbu"
fullname2="Subbu Kumar"
userpass2="aa"
shell2="fish"

# arch-chroot /mnt useradd -m -G wheel -s /bin/${shell2} -c ${fullname2} $username2

# printf "%s\n%s" "${userpass2}" "${userpass2}" | arch-chroot /mnt passwd "$username2"



# useradd -G users,wheel -s /bin/bash ${username}
# chpasswd ${username} <<-EOF
# ${userpass}
# ${userpass}
# EOF

# passwd -i "Enter your new password:\nConfirm your new password:"


# passwd ${username} | cat <<EOF
# ${userpass}
# ${userpass}
# EOF



#!/bin/bash

# Change the value of USERNAME to the username you want to change the password for
USERNAME="Rishu"

# Change the value of NEW_PASSWORD to the new password you want to set
NEW_PASSWORD="AA"

# echo "${NEW_PASSWORD}\n${NEW_PASSWORD}" | passwd $USERNAME 

useradd -G users,wheel -s /bin/bash ${USERNAME}


file="passwd.txt"
cat $file | passwd $USERNAME