# Author : Bibhuti Bhushan
# Github : https://github.com/Bibhuti1221Bhushan/Installer

# USER SPECIFIC VARIABLES :        
# ~~~~~~~~~~~~~~~~~~~~~~~~~
FULL_NAME="Bibhuti Bhushan"
USER_NAME="Bibhuti"
USER_PASS="////"
ROOT_PASS="////"
HOST_NAME="iTunes"
TIME_ZONE="Asia/Kolkata"
INPUT_MAP="us"
LOCALE="en_US.UTF-8"

# DISK NAME : IN WHICH YOU WANT TO INSTALL
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DISK=/dev/sda

# BOOT PARTITION SIZE IN MB : MINIMUM SIZE IS 500 MB
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
BOOT_SIZE=500

# ROOT PARTITION SIZE IN GB : MINIMUM SIZE IS 20 GB
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ROOT_SIZE=20                              # NOTE : IF NO HOME PARTITION IS SELECTED THEN SIZE OF ROOT PARTITION IS THE REMAINING SPACE

# HOME PARTITION : 
# ~~~~~~~~~~~~~~~~
HOME=1                                    # 0 = NO HOME PARTITION , 1 = HOME PARTITION - REMAINING SPACE & 2 = CUSTOM HOME PARTITION
CUSTOM_HOME=/dev/sda2

# SWAP SIZE :
# ~~~~~~~~~~~
SWAP=3                                    # 0 = NO SWAP , 1 = ZRAM, 2 = SWAP PARTITION & 3 = SWAP FILE
ZRAM_SIZE=2                               # SET SIZE OF ZRAM - 0.5 x RAM SIZE MUST BE IN GB
SWAP_SIZE=8                               # SET SIZE OF SWAP PARTITION OR SWAP FILE - 2 x RAM SIZE MUST BE IN GB

# BOOT-LOADER :
# ~~~~~~~~~~~~~
BOOT_LOADER=1                             # 1 = SYSTEMD-BOOT & 2 = GRUB

# KERNEL PACKAGES :
# ~~~~~~~~~~~~~~~~~
KERNEL="linux-lts"

# EXTRA PACKAGES :
# ~~~~~~~~~~~~~~~~
EDITOR="micro"

# DOT-FILES REPOSITORY :
# ~~~~~~~~~~~~~~~~~~~~~~
DOT_FILES="https://github.com/Bibhuti1221Bhushan/Personal-Dots"
